language: python
python:
  - "3.6"

# Using the Firefox addon in headless mode
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
# install geckodriver
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - nosetests tests